#!/bin/bash


# This functions add the go code to the *main.go* file
# Then tells the user to test the project
addCode(){
	echo '//File: cmd/api/main.go

	package main

	import "fmt"
	
	func main() {
	fmt.Println("Hello World!")
	}' > cmd/api/main.go

	echo "I have created a *main.go* file for you to test the directory structure."
	sleep 3
	echo "Type *go run ./cmd/api* at the root direcotry of your project to test your project."
	sleep 3
	echo "Thanks you. Goodbye"

}

# This functions initially takes the user to the home directory of the current user
# Then creates the require project directories and files
createDir() {
	cd
	mkdir -p  /home/"$USER"/"$DIR"
	cd "$DIR"
	mkdir -p bin cmd/api internals migrations remote
	clear
	echo "All directories were created succesfully!"
	sleep 3
	go mod init "$DIR"."$ID".net
	clear
	go mod tidy
	clear
	touch MakeFile
	touch cmd/api/main.go
	echo "All required files created succesfully!"
	sleep 3
	clear
	addCode
}

#Start of the script
# Variables are initialized with the arguments passed in by the user
DIR="$1"
ID="$2"

# If check to ensure the user is entering two arguments when calling the script
if [[ -z "$DIR" || -z "$ID" ]]; then
	clear
	echo "Directory name is ["$DIR"] and Identifier name is ["$ID"]."
	echo "You need to provide two arguments for this script to work."
	echo "<<script_name>> <root directory name> <identifier name>"
	sleep 5
	clear
	exit 1
fi

echo "I am about to create a directory structure named "$DIR"." 

actionCont() {
		read -e -p "Do you want me to continue? [Yes/no]:" USERANS
}

actionCont
while [[ "$USERANS" != "Yes" && "$USERANS" != "no" ]]; do
	clear
	echo "Invalid Answer"
	sleep 1
	clear
	actionCont
done

if [[ "$USERANS" = "Yes" ]]; then
	clear
	echo "Creating "$DIR" directory structure..."
	sleep 3
	clear
	createDir "$DIR" "$ID"


else
	clear
	echo ""$DIR" Directory Creation was ABORTED!"
	sleep 4
	clear
fi


